## Problem Statement
- To analyze sales data of the past 5 years and identify pattern,trends , insights.

## Objective
 - Identify Highest and lowest Sales year
 - Visualize sales trends
 - Analyze yearly Sale

## System Architecture

  Input Data (CSV)<br>
        ↓<br>
  Data Cleaning (Pandas)<br>
        ↓<br>
 Data Analysis (Grouping, Calculations)<br>
        ↓<br>
 Visualization (Matplotlib)<br>
        ↓<br>
 Insights / Output<br>

In [2]:
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
df=pd.read_csv("Sample - Superstore.csv")

In [6]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,US-2022-103800,03-01-22,07-01-22,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,...,77095,Central,OFF-PA-10000174,Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",16.448,2,0.2,5.5512
1,2,US-2022-112326,04-01-22,08-01-22,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-BI-10004094,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,3.540,2,0.8,-5.4870
2,3,US-2022-112326,04-01-22,08-01-22,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-LA-10003223,Office Supplies,Labels,Avery 508,11.784,3,0.2,4.2717
3,4,US-2022-112326,04-01-22,08-01-22,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-ST-10002743,Office Supplies,Storage,SAFCO Boltless Steel Shelving,272.736,3,0.2,-64.7748
4,5,US-2022-141817,05-01-22,12-01-22,Standard Class,MB-18085,Mick Brown,Consumer,United States,Philadelphia,...,19143,East,OFF-AR-10003478,Office Supplies,Art,Avery Hi-Liter EverBold Pen Style Fluorescent ...,19.536,3,0.2,4.8840

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10194 entries, 0 to 10193
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          10194 non-null  int64
 1   Order ID        10194 non-null  object
 2   Order Date      10194 non-null  object
 3   Ship Date       10194 non-null  object
 4   Ship Mode       10194 non-null  object
 5   Customer ID     10194 non-null  object
 6   Customer Name   10194 non-null  object
 7   Segment         10194 non-null  object
 8   Country/Region  10194 non-null  object
 9   City            10194 non-null  object
 10  State/Province  10194 non-null  object
 11  Postal Code     10194 non-null  object
 12  Region          10194 non-null  object
 13  Product ID      10194 non-null  object
 14  Category        10194 non-null  object
 15  Sub-Category    10194 non-null  object
 16  Product Name    10194 non-null  object
 17  Sales           10194 non-null  float64
 18  Quantity        10194 non-null  int64
 19  Discount        10194 non-null  float64
 20  Profit          10194 non-null  float64
dtypes: float64(3), int64(2), object(16)
memory usage: 1.6+ MB

In [12]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country/Region', 'City',
       'State/Province', 'Postal Code', 'Region', 'Product ID', 'Category',
       'Sub-Category', 'Product Name', 'Sales', 'Quantity', 'Discount',
       'Profit'],
      dtype='object')

In [13]:
df2=df[['Order Date','Sales','Country/Region','Category','Profit']]

In [20]:
df2.head()

  Order Date    Sales Country/Region         Category   Profit  Year
0 2022-03-01   16.448  United States  Office Supplies   5.5512  2022
1 2022-04-01    3.540  United States  Office Supplies  -5.4870  2022
2 2022-04-01   11.784  United States  Office Supplies   4.2717  2022
3 2022-04-01  272.736  United States  Office Supplies -64.7748  2022
4 2022-05-01   19.536  United States  Office Supplies   4.8840  2022

In [18]:
df2['Order Date']=pd.to_datetime(df2['Order Date'])
df2['Year']=df2['Order Date'].dt.year

C:\Users\SAAD MIRZA\AppData\Local\Temp\ipykernel_11788\476720728.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df2['Order Date']=pd.to_datetime(df2['Order Date'])
C:\Users\SAAD MIRZA\AppData\Local\Temp\ipykernel_11788\476720728.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['Order Date']=pd.to_datetime(df2['Order Date'])
C:\Users\SAAD MIRZA\AppData\Local\Temp\ipykernel_11788\476720728.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['Year']=df2['Order Date'].dt.year

In [19]:
df2.dtypes

Order Date        datetime64[ns]
Sales                    float64
Country/Region            object
Category                  object
Profit                   float64
Year                       int32
dtype: object

In [21]:
df2['Year'].unique()

array([2022, 2023, 2024, 2025], dtype=int32)